import { StyleSheet, Text, View } from 'react-native';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
    //   justifyContent: 'center',
    //   backgroundColor: 'orange',
      paddingTop: 50,
      color: 'white',
    },
    nav: {
        flex: 1,
        // backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        // top: 30,
        // backgroundColor: '#fc9003',
        width: '100%',
        height: '20%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 45,
        color: 'white',
    },
    userData: {
        position: 'absolute',
        top: 150,
        width: '100%',
        height: '10%',
        display: 'flex',
        fontWeight: 'bold',
        fontSize: 65,
        alignItems: 'center', 
    },
    userName: {
        fontWeight: 'bold',
        fontSize: 65,
        color: 'white',
    },
    userLevel: {
        fontWeight: 'bold',
        fontSize: 30,
        color: 'white',
    },
    rank: {
        fontWeight: 'bold',
        fontSize: 40,
        color: 'white',
    },
    recentMatches: {
        position: 'absolute',
        top: 300,
        width: '40%',
        height: '10%',
        display: 'flex',
        fontWeight: 'bold',
        fontSize: 65,
        alignItems: 'center',
        backgroundColor: 'white',
        margin: 100,
        right: '25%',
        borderRadius: 20,
        justifyContent: 'center',
    },
    smthn: {
        position: 'absolute',
        top: 400,
        width: '40%',
        height: '10%',
        display: 'flex',
        fontWeight: 'bold',
        fontSize: 65,
        alignItems: 'center',
        backgroundColor: 'white',
        margin: 100,
        left: '25%',
        borderRadius: 20,
        justifyContent: 'center',
    },
    mtitle: {
        fontWeight: 'bold',
        fontSize: 15,
        color: 'black',
    },
    avg: {
        fontWeight: 'bold',
        fontSize: 30,
        color: 'black',
        alignSelf: 'center',
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        width: '95%',
        height: '10%',
        display: 'flex',
        fontWeight: 'bold',
        fontSize: 65,
        alignItems: 'center',
        backgroundColor: 'white',
        margin: 25,
        padding: 10,
        justifyContent: 'center',
        // left: '25%',
        borderRadius: 20,
    },
    ftitle: {
        fontWeight: 'bold',
        fontSize: 15,
        color: 'black',
        alignSelf: 'center',
    },
});
  

export default styles;